### PR TITLE
feat: PC-13263 New kind: Reports

### PR DESCRIPTION
**Pull request by natalialanga**
## Summary

Add posibility to apply/delete/get reports.

## Related changes

https://github.com/nobl9/nobl9-go/pull/495

## Release Notes

New `Report` kind for handling creating, updating and deleting reports. This feature is currently in early access, and is available only on demand. If you want to utilize SDK for reports management, please reach out to Nobl9 Support.

### CODE REVIEW

**Comment by nieomylnieja** [comment]
take a look at:
- https://github.com/nobl9/sloctl/blob/55eece4483c6218e06ac2b945d9aba9a5ee56c5e/internal/flags.go#L59
- https://github.com/nobl9/sloctl/blob/55eece4483c6218e06ac2b945d9aba9a5ee56c5e/internal/flags.go#L87

If Reports are supporting labels filtering or are project scoped you will need to addd it to these lists ;)

**Comment by natalialanga** [comment]
> * sloctl/internal/flags.go

Thanks! Reports do not support labels filtering and are not project scoped, so we're good.

**Review by lukasz-dobek — APPROVED** [review]

**Comment by nieomylnieja** [comment]
you're missing sloctl tests here :)
please add them before merging this PR

https://github.com/nobl9/sloctl/tree/main/test

**Comment by lukasz-dobek** [comment]
@nieomylnieja locally run e2e tests and all were successful 🎉 

```
43 tests, 0 failures
```

I'd appreciate it if you could check this PR once more (hopefully the last time 😸)

**Review by nieomylnieja — APPROVED** [review]

**Pull request merged**
